name = "bingada"
description = "Bingo application in GTKAda"
version = "1.0.0"

authors = ["Javier Fuica Fernández", "Manuel Gómez"]
maintainers = ["Manuel Gómez <mgrojo@gmail.com>"]
maintainers-logins = ["mgrojo"]

executables = ["bingada"]

[[depends-on]]  # This line was added by `alr with`
gtkada = "^21.0.0"  # This line was added by `alr with`


[[depends-on]]  # This line was added by `alr with`
asfml = "^2.5.0"  # This line was added by `alr with`
