name: Ada (GNAT)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain and libraries
      run: >
        sudo apt-get update && 
        sudo apt-get install gnat-7 gprbuild make libcanberra-dev libgtkada16.1.0-dev

    - name: Build
      run: >
        cd libs/canberra-ada
        make
        cd ../..
        gprbuild -j0 -p

